### ISSUE TITLE
BUG - Build error on client / server

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#102]
Bug discovered on friday 07/12 - Raffi took afternoon to fix it.

**Comment by Natisolar** [comment]
Please @raffi-bedoyan-azumo complete this card with the bug details to have some reference if it happens again. Then close it. TKS!

**Comment by raffi-bedoyan-azumo** [comment]
There was an error during the build time which was about the scope of the libraries. Some libraries that only run in Nodejs env, were trying to be built in the client and that's not possible. What I did to fix this was to manually disable some libraries only on the client side to prevent the  building in a wrong way.

```
// next.config.mjs

webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        net: false,
        fs: false,
        child_process: false,
        http2: false,
        tls: false,
        dns: false
      }
    }

    return config
  },
```
