### ISSUE TITLE
UNIT TESTING | Tasks to test S7 features - Chris

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#104]
Unit testing of:

#56 #90 #94 #96

Edit:

Removing #97 as it hasn't been implemented yet

**Comment by christian-herrera-azumo** [comment]
- Added tests related to #56 
- Added Github action for running tests on push. Check the first execution [here](https://github.com/social-sonar/Socialsonar/actions/runs/10118998132/job/27986723986)

**Comment by christian-herrera-azumo** [comment]
- Added tests related to #94 and #96
