### ISSUE TITLE
Make improve contacts interactive 

### ISSUE THREAD

**Issue by posix4e** [social-sonar/Socialsonar#30]

**Comment by agrasso-azumo** [comment]
we don’t wanna change or improve any contact without the user agreeing to that improvement
We just suggest it and they authorize it

**Comment by Natisolar** [comment]
@posix4e  Please can you confirm if what Anto and the guys comment on Discord is ok? or do you want to have an improvement here?

**Comment by posix4e** [comment]
Seems ok

**Comment by Natisolar** [comment]
@posix4e Ok! we proceed to close the task.
