### ISSUE TITLE
Link test event scheduling to allow people to book meetings.

### ISSUE THREAD

**Issue by posix4e** [social-sonar/Socialsonar#32]
Verify wheather this function is on according to task #43

**Comment by christian-herrera-azumo** [comment]
Fixed bugs regarding timezone. Added 2 points to estimate due to it.

**Fixes were added directly to main**: [Changelog](https://github.com/blackbookcleaner/Socialsonar/compare/4efceddd957cffc870f12d500bd71dcd9f4447de...cc7baa40548f6ca35f09c7064464b63ae2ae7b9c)
