### ISSUE TITLE
CALENDAR | Spike: Appointment Scheduling Feature - Timezone 

### ISSUE THREAD

**Issue by agrasso-azumo** [social-sonar/Socialsonar#44]
Integrate advanced automatic timezone detection and travel planning features to ensure accurate scheduling across different locations.

AC:

1. Established home basis with 2 possible options.

**Comment by agrasso-azumo** [comment]
Develop a feature that detects when a user travels out of town and facilitates easy scheduling of meetings with multiple contacts for a week or two.

**Comment by Natisolar** [comment]
Goal: your page on the internet to connect with you
THe basic features of [about.me/posix4e](http://about.me/posix4e) but stripped down
Should be mostly generated automatically mostly from linkedin and existing self card
 If I’m logged in, my schedule should show up

**Comment by Natisolar** [comment]
1. Establish Home base (two options)
2. Detect a travel event (plane tkt - person manual scheaduling) 
3. Notification when travelling approaches
4. Notification of event comming --> User has an event scheduled on a city -

**Comment by christian-herrera-azumo** [comment]
Resulting issues: #94, #95, #96, #97
