### ISSUE TITLE
CALENDAR | Sync/Backup/Restore to Google Calendar

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#56]
Implement functionality to synchronize, backup, and restore calendar events google.

**Comment by Natisolar** [comment]
![Image](https://github.com/social-sonar/Socialsonar/assets/171864604/7fd3210d-0732-4d83-bbd2-e59fb6588271)

**Comment by christian-herrera-azumo** [comment]
New design and features



![Image](https://github.com/social-sonar/Socialsonar/assets/140095738/b74110dc-ff3f-4636-8178-b9a316fbe51b)



![Image](https://github.com/social-sonar/Socialsonar/assets/140095738/394e76bb-bbcb-4cd5-97b4-33060aff4c29)
