### ISSUE TITLE
CALENDAR | Appointment Scheduling feature - Travel event

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#68]
Integrate advanced automatic travel planning features to ensure accurate scheduling across different locations.

AC: 
1. Detect on calendar a travel event (ex. plane tkt - person manual scheaduling)
4. Notification when a travelling event approaches. 
5. Notification of upcomming event--> User has an acheduled event on a city wich SS doesn´t detect an booked travel event.

**Comment by christian-herrera-azumo** [comment]
This issue has been split into the following more specific issues: #94, #95, #96, #97
