### ISSUE TITLE
CONTACTS | Deduplication review

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#75]
Review feature - 
Enhance user experience - add result estatus after the execution.

**Comment by zaldivards** [comment]
Paused. Fixing bug related to the middleware

**Comment by christian-herrera-azumo** [comment]
Paused. Fixing bug related to the middleware

**Comment by christian-herrera-azumo** [comment]
### Possible duplicated contacts found - UI

![Image](https://github.com/social-sonar/Socialsonar/assets/140095738/90662032-5778-4e47-8dc3-b9852fddff28)

### No duplicates found - UI

![Image](https://github.com/social-sonar/Socialsonar/assets/140095738/25c5c9a9-4028-4811-a8f8-be29479678f9)

Users will see either of the above UIs in the contacts list section
