### ISSUE TITLE
CONTACTS | duplication not working

### ISSUE THREAD

**Issue by Natisolar** [social-sonar/Socialsonar#85]
It doesn’t validate a duplicate number.

**Comment by zaldivards** [comment]
Updated how duplicate contacts are shown and resolved. This change ensures correct resolutions.

## Before

![Image](https://github.com/user-attachments/assets/de6bd004-ea92-4175-a709-24da6f67c071)

## Now

![Image](https://github.com/user-attachments/assets/5ed2039f-d045-4b7f-a8d1-795516d88749)

**Comment by christian-herrera-azumo** [comment]
Updated how duplicate contacts are shown and resolved. This change ensures correct resolutions.

## Before

![Image](https://github.com/user-attachments/assets/de6bd004-ea92-4175-a709-24da6f67c071)

## Now

![Image](https://github.com/user-attachments/assets/5ed2039f-d045-4b7f-a8d1-795516d88749)

**Comment by christian-herrera-azumo** [comment]
Added requested changes
